name: Run Ansible Playbook

on:
  # Triggers the workflow on push or pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment and install Ansible
      - name: Set up Python and Install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Step 3: Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook playbook.yml -i inventory.yml

      # Optional Step: Run Ansible Lint
      - name: Run Ansible Lint (optional)
        run: |
          pip install ansible-lint
          ansible-lint playbook.yml
